version: '3.4'

services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '3050:80'
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - DB_CONN_STRING=mongodb://mongo:27017/recaura
      - JWT_SECRET=recauradocker
      - ALLOWED_ORIGINS=
    depends_on:
      - mongo
  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'

volumes:
  mongo:
