/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.3.0.0 (NJsonSchema v10.1.11.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming



export interface IGetCaseFileVm {
    id: number;
    patientId: number;
    name: string;
    created: string;
    consultations: ICaseFileConsultationVm[];
}

export interface ICaseFileConsultationVm {
    id: number;
    date: string;
    number: number;
    practitionerId: number;
}

export interface IGetPatientsVm {
    patients: IPatientVm[];
}

export interface IPatientVm {
    id: number;
    firstName: string;
    lastName: string;
    dob: string;
}

export interface IPersonVm {
    id: number;
    honorific: Honorific;
    firstName: string;
    lastName: string;
    dob: string;
    email: string;
    countryCode: string;
    homePhone: string;
    mobilePhone: string;
    gender: Gender;
}

export interface IGetPatientVm extends IPersonVm {
    occupation: string;
    caseFiles: IPatientCaseFileVm[];
}

export interface IPatientCaseFileVm {
    id: number;
    name: string;
}

/** 0 = Mr 1 = Mrs 2 = Miss 3 = Ms 4 = Master 5 = Mx 6 = M 7 = Sir 8 = Madam 9 = Dr 10 = Prof */
export enum Honorific {
    Mr = 0,
    Mrs = 1,
    Miss = 2,
    Ms = 3,
    Master = 4,
    Mx = 5,
    M = 6,
    Sir = 7,
    Madam = 8,
    Dr = 9,
    Prof = 10,
}

/** 0 = PreferNotToSay 1 = Male 2 = Female 3 = Other */
export enum Gender {
    PreferNotToSay = 0,
    Male = 1,
    Female = 2,
    Other = 3,
}